services:
  application:
    build:
      context: .
      args:
        ACTIVE_PROFILE: dev
    ports:
      - "8080:8080"

  newsql:
    build:
      context: .
      dockerfile: Dockerfile.db
      
    ports:
      - "3306:3306"

